// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Qp9gmKpnYZ3ipqspGhRwc6EAnnD90AE',
    appId: '1:345728532216:web:dbfd02d03fa984910d450d',
    messagingSenderId: '345728532216',
    projectId: 'modit-a81ba',
    authDomain: 'modit-a81ba.firebaseapp.com',
    storageBucket: 'modit-a81ba.firebasestorage.app',
    measurementId: 'G-NRC7MTMPW3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH5gY0nEYJUxGljVbLXTRoIs_XCijYUxw',
    appId: '1:345728532216:android:e09017154ba086260d450d',
    messagingSenderId: '345728532216',
    projectId: 'modit-a81ba',
    storageBucket: 'modit-a81ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9-ysmjavP8IqUWWE6HvnyuTI0bQmQDAU',
    appId: '1:345728532216:ios:a1d21808237a71fc0d450d',
    messagingSenderId: '345728532216',
    projectId: 'modit-a81ba',
    storageBucket: 'modit-a81ba.firebasestorage.app',
    iosBundleId: 'com.example.moditapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9-ysmjavP8IqUWWE6HvnyuTI0bQmQDAU',
    appId: '1:345728532216:ios:a1d21808237a71fc0d450d',
    messagingSenderId: '345728532216',
    projectId: 'modit-a81ba',
    storageBucket: 'modit-a81ba.firebasestorage.app',
    iosBundleId: 'com.example.moditapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1Qp9gmKpnYZ3ipqspGhRwc6EAnnD90AE',
    appId: '1:345728532216:web:24c03a4e2b6f2ab00d450d',
    messagingSenderId: '345728532216',
    projectId: 'modit-a81ba',
    authDomain: 'modit-a81ba.firebaseapp.com',
    storageBucket: 'modit-a81ba.firebasestorage.app',
    measurementId: 'G-ZV0ZRMHYHJ',
  );
}
